modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="sparky_mod"
version="1.0"
displayName="SparkyMod"
displayURL="None"
credits="by pinne"
authors="MOON"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sparky_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration